# -*- coding: utf-8 -*-
"""final-project-mathematicalfoundations.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Dvw9H6ZrdDvgEBF82mTr05AQnH3WeQVz
"""

import numpy as np
import matplotlib.pyplot as plt

# --- Gauss elimination to solve Ax = b ---
def gauss_elimination(A, b):
    A = A.astype(float)
    b = b.astype(float)
    n = len(b)
    for i in range(n):
        max_row = np.argmax(np.abs(A[i:, i])) + i
        if max_row != i:
            A[[i, max_row]] = A[[max_row, i]]
            b[i], b[max_row] = b[max_row], b[i]
        for j in range(i+1, n):
            factor = A[j,i] / A[i,i]
            A[j,i:] -= factor * A[i,i:]
            b[j] -= factor * b[i]
    x = np.zeros(n)
    for i in range(n-1, -1, -1):
        x[i] = (b[i] - np.dot(A[i,i+1:], x[i+1:])) / A[i,i]
    return x

# Polynomial interpolation per pixel
def poly_interpolate_pixel(times, values, t_new):
    A = np.vander(times, increasing=False)
    coeffs = gauss_elimination(A.copy(), values.copy())
    powers = np.array([t_new**p for p in range(len(times)-1, -1, -1)])
    return np.dot(coeffs, powers), coeffs

# Gradient descent step to refine coeffs (single pixel)
def grad_descent_step(coeffs, t_new, true_val, lr=0.01):
    powers = np.array([t_new**p for p in range(len(coeffs)-1, -1, -1)])
    pred = np.dot(coeffs, powers)
    error = pred - true_val
    grad = 2 * error * powers
    coeffs -= lr * grad
    return coeffs, error**2

# Interpolation + optimization function
def interpolate_frames_poly(frame0, frame1, frame2, t_new=1.5, lr=0.01, steps=50):
    times = np.array([0, 1, 2])
    h, w = frame0.shape
    interp_frame = np.zeros((h, w))
    coeffs_all = np.zeros((h, w, 3))

    # Compute initial coeffs and initial interpolation
    for i in range(h):
        for j in range(w):
            values = np.array([frame0[i,j], frame1[i,j], frame2[i,j]])
            _, coeffs = poly_interpolate_pixel(times, values, t_new)
            coeffs_all[i,j,:] = coeffs

    interp_initial = np.zeros((h,w))
    for i in range(h):
        for j in range(w):
            coeffs = coeffs_all[i,j,:]
            powers = np.array([t_new**p for p in range(2, -1, -1)])
            interp_initial[i,j] = np.dot(coeffs, powers)

    # Simulated ground truth mid-frame: moving square slightly shifted + noise
    true_mid = (frame1 + frame2) / 2
    true_mid = np.clip(true_mid + 0.05*np.random.randn(h,w), 0, 1)

    # Gradient descent optimization on coeffs per pixel
    for step in range(steps):
        total_loss = 0
        for i in range(h):
            for j in range(w):
                coeffs = coeffs_all[i,j,:]
                true_val = true_mid[i,j]
                coeffs, loss = grad_descent_step(coeffs, t_new, true_val, lr)
                coeffs_all[i,j,:] = coeffs
                total_loss += loss
        if step % 10 == 0:
            print(f"Step {step}, total loss: {total_loss:.6f}")

    # Final refined interpolation frame
    for i in range(h):
        for j in range(w):
            coeffs = coeffs_all[i,j,:]
            powers = np.array([t_new**p for p in range(2, -1, -1)])
            interp_frame[i,j] = np.dot(coeffs, powers)

    interp_frame = np.clip(interp_frame, 0, 1)

    return interp_initial, interp_frame, true_mid

# --- Generate moving square frames ---
def create_frame(h, w, square_pos):
    frame = np.zeros((h, w))
    size = 15
    x_start = square_pos
    x_end = min(w, square_pos + size)
    y_start = h // 3
    y_end = y_start + size
    frame[y_start:y_end, x_start:x_end] = 1.0
    return frame

h, w = 50, 80
frame0 = create_frame(h, w, 10)
frame1 = create_frame(h, w, 12)
frame2 = create_frame(h, w, 17)

# Run interpolation + refinement
interp_initial, interp_refined, true_mid = interpolate_frames_poly(frame0, frame1, frame2)

# Visualize results
fig, axs = plt.subplots(2, 4, figsize=(16, 8))

axs[0,0].imshow(frame0, cmap='gray'); axs[0,0].set_title('Frame 0'); axs[0,0].axis('off')
axs[0,1].imshow(frame1, cmap='gray'); axs[0,1].set_title('Frame 1'); axs[0,1].axis('off')
axs[0,2].imshow(frame2, cmap='gray'); axs[0,2].set_title('Frame 2'); axs[0,2].axis('off')
axs[0,3].imshow(true_mid, cmap='gray'); axs[0,3].set_title('Simulated Ground Truth'); axs[0,3].axis('off')


axs[1,0].imshow(interp_initial, cmap='gray'); axs[1,0].set_title('Initial Poly Interp'); axs[1,0].axis('off')
axs[1,1].imshow(interp_refined, cmap='gray'); axs[1,1].set_title('Refined Interp (GD)'); axs[1,1].axis('off')

# Difference heatmaps
diff_init = np.abs(true_mid - interp_initial)
diff_refined = np.abs(true_mid - interp_refined)

axs[1,2].imshow(diff_init, cmap='hot'); axs[1,2].set_title('Diff Initial vs True'); axs[1,2].axis('off')
axs[1,3].imshow(diff_refined, cmap='hot'); axs[1,3].set_title('Diff Refined vs True'); axs[1,3].axis('off')

plt.tight_layout()
plt.show()

# Print numeric errors
mse_init = np.mean(diff_init**2)
mse_refined = np.mean(diff_refined**2)
print(f"MSE initial interpolation vs ground truth: {mse_init:.6f}")
print(f"MSE refined interpolation vs ground truth: {mse_refined:.6f}")
import numpy as np
import matplotlib.pyplot as plt

# --- Gauss elimination to solve Ax = b ---
def gauss_elimination(A, b):
    A = A.astype(float)
    b = b.astype(float)
    n = len(b)
    for i in range(n):
        max_row = np.argmax(np.abs(A[i:, i])) + i
        if max_row != i:
            A[[i, max_row]] = A[[max_row, i]]
            b[i], b[max_row] = b[max_row], b[i]
        for j in range(i+1, n):
            factor = A[j,i] / A[i,i]
            A[j,i:] -= factor * A[i,i:]
            b[j] -= factor * b[i]
    x = np.zeros(n)
    for i in range(n-1, -1, -1):
        x[i] = (b[i] - np.dot(A[i,i+1:], x[i+1:])) / A[i,i]
    return x

# Polynomial interpolation per pixel
def poly_interpolate_pixel(times, values, t_new):
    A = np.vander(times, increasing=False)
    coeffs = gauss_elimination(A.copy(), values.copy())
    powers = np.array([t_new**p for p in range(len(times)-1, -1, -1)])
    return np.dot(coeffs, powers), coeffs

# Gradient descent step to refine coeffs (single pixel)
def grad_descent_step(coeffs, t_new, true_val, lr=0.01):
    powers = np.array([t_new**p for p in range(len(coeffs)-1, -1, -1)])
    pred = np.dot(coeffs, powers)
    error = pred - true_val
    grad = 2 * error * powers
    coeffs -= lr * grad
    return coeffs, error**2

# Interpolation + optimization function
def interpolate_frames_poly(frame0, frame1, frame2, t_new=1.5, lr=0.01, steps=50):
    times = np.array([0, 1, 2])
    h, w = frame0.shape
    interp_frame = np.zeros((h, w))
    coeffs_all = np.zeros((h, w, 3))

    # Compute initial coeffs and initial interpolation
    for i in range(h):
        for j in range(w):
            values = np.array([frame0[i,j], frame1[i,j], frame2[i,j]])
            _, coeffs = poly_interpolate_pixel(times, values, t_new)
            coeffs_all[i,j,:] = coeffs

    interp_initial = np.zeros((h,w))
    for i in range(h):
        for j in range(w):
            coeffs = coeffs_all[i,j,:]
            powers = np.array([t_new**p for p in range(2, -1, -1)])
            interp_initial[i,j] = np.dot(coeffs, powers)

    # Simulated ground truth mid-frame: moving square slightly shifted + noise
    true_mid = (frame1 + frame2) / 2
    true_mid = np.clip(true_mid + 0.05*np.random.randn(h,w), 0, 1)

    # Gradient descent optimization on coeffs per pixel
    for step in range(steps):
        total_loss = 0
        for i in range(h):
            for j in range(w):
                coeffs = coeffs_all[i,j,:]
                true_val = true_mid[i,j]
                coeffs, loss = grad_descent_step(coeffs, t_new, true_val, lr)
                coeffs_all[i,j,:] = coeffs
                total_loss += loss
        if step % 10 == 0:
            print(f"Step {step}, total loss: {total_loss:.6f}")

    # Final refined interpolation frame
    for i in range(h):
        for j in range(w):
            coeffs = coeffs_all[i,j,:]
            powers = np.array([t_new**p for p in range(2, -1, -1)])
            interp_frame[i,j] = np.dot(coeffs, powers)

    interp_frame = np.clip(interp_frame, 0, 1)

    return interp_initial, interp_frame, true_mid


# --- Generate moving square frames ---
def create_frame(h, w, square_pos):
    frame = np.zeros((h, w))
    size = 15
    x_start = square_pos
    x_end = min(w, square_pos + size)
    y_start = h // 3
    y_end = y_start + size
    frame[y_start:y_end, x_start:x_end] = 1.0
    return frame

h, w = 50, 80
frame0 = create_frame(h, w, 10)
frame1 = create_frame(h, w, 12)
frame2 = create_frame(h, w, 17)

# Run interpolation + refinement
interp_initial, interp_refined, true_mid = interpolate_frames_poly(frame0, frame1, frame2)

# Visualize results
fig, axs = plt.subplots(2, 4, figsize=(16, 8))

axs[0,0].imshow(frame0, cmap='gray'); axs[0,0].set_title('Frame 0'); axs[0,0].axis('off')
axs[0,1].imshow(frame1, cmap='gray'); axs[0,1].set_title('Frame 1'); axs[0,1].axis('off')
axs[0,2].imshow(frame2, cmap='gray'); axs[0,2].set_title('Frame 2'); axs[0,2].axis('off')
axs[0,3].imshow(true_mid, cmap='gray'); axs[0,3].set_title('Simulated Ground Truth'); axs[0,3].axis('off')

axs[1,0].imshow(interp_initial, cmap='gray'); axs[1,0].set_title('Initial Poly Interp'); axs[1,0].axis('off')
axs[1,1].imshow(interp_refined, cmap='gray'); axs[1,1].set_title('Refined Interp (GD)'); axs[1,1].axis('off')

# Difference heatmaps
diff_init = np.abs(true_mid - interp_initial)
diff_refined = np.abs(true_mid - interp_refined)

axs[1,2].imshow(diff_init, cmap='hot'); axs[1,2].set_title('Diff Initial vs True'); axs[1,2].axis('off')
axs[1,3].imshow(diff_refined, cmap='hot'); axs[1,3].set_title('Diff Refined vs True'); axs[1,3].axis('off')

plt.tight_layout()
plt.show()

# Print numeric errors
mse_init = np.mean(diff_init**2)
mse_refined = np.mean(diff_refined**2)
print(f"MSE initial interpolation vs ground truth: {mse_init:.6f}")
print(f"MSE refined interpolation vs ground truth: {mse_refined:.6f}")